import { bookLang } from "../book-model/bookLang";
import { Ibook } from "../book-model/Ibook";

// export const Books: Ibook[] = [
//   {
//     Id: 1,
//     Title: "Book 1",
//     Description: "Description 1",
//     ISBN: "ISBN 1",
//     Price: 10,
//     DiscountPercentage: 10,
//     PublishedDate: new Date("2022-01-01"),
//     PageCount: 100,
//     Language: bookLang.ar,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Hardcover",
//     StockQuantity: 10,
//     AuthorId: 1,
//     AuthorName: "Author One",
//     PublisherId: 1,
//     PublisherName: "Publisher One",
//     CategoryIds: [1],
//     CategoryNames: ["Fiction"],
//     IsActive: true,
//     Rating: 4.5,
//   },
//   {
//     Id: 2,
//     Title: "Book 2",
//     Description: "Description 2",
//     ISBN: "ISBN 2",
//     Price: 20,
//     DiscountPercentage: 15,
//     PublishedDate: new Date("2022-02-01"),
//     PageCount: 150,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 20,
//     AuthorId: 2,
//     AuthorName: "Author Two",
//     PublisherId: 2,
//     PublisherName: "Publisher Two",
//     CategoryIds: [2],
//     CategoryNames: ["Science"],
//     IsActive: true,
//     Rating: 4.0,
//   },
//   {
//     Id: 3,
//     Title: "Book 3",
//     Description: "Description 3",
//     ISBN: "ISBN 3",
//     Price: 30,
//     DiscountPercentage: 5,
//     PublishedDate: new Date("2022-03-01"),
//     PageCount: 200,
//     Language: bookLang.ar,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "eBook",
//     StockQuantity: 15,
//     AuthorId: 3,
//     AuthorName: "Author Three",
//     PublisherId: 3,
//     PublisherName: "Publisher Three",
//     CategoryIds: [3],
//     CategoryNames: ["History"],
//     IsActive: false,
//     Rating: 3.8,
//   },
//   {
//     Id: 4,
//     Title: "Book 4",
//     Description: "Description 4",
//     ISBN: "ISBN 4",
//     Price: 25,
//     DiscountPercentage: 20,
//     PublishedDate: new Date("2022-04-01"),
//     PageCount: 180,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Hardcover",
//     StockQuantity: 8,
//     AuthorId: 4,
//     AuthorName: "Author Four",
//     PublisherId: 4,
//     PublisherName: "Publisher Four",
//     CategoryIds: [2, 3],
//     CategoryNames: ["Science", "History"],
//     IsActive: true,
//     Rating: 4.2,
//   },
//   {
//     Id: 5,
//     Title: "Book 5",
//     Description: "Description 5",
//     ISBN: "ISBN 5",
//     Price: 18,
//     DiscountPercentage: 12,
//     PublishedDate: new Date("2022-05-01"),
//     PageCount: 90,
//     Language: bookLang.ar,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 30,
//     AuthorId: 5,
//     AuthorName: "Author Five",
//     PublisherId: 5,
//     PublisherName: "Publisher Five",
//     CategoryIds: [1],
//     CategoryNames: ["Fiction"],
//     IsActive: false,
//     Rating: 3.5,
//   },
//   {
//     Id: 6,
//     Title: "Book 6",
//     Description: "Description 6",
//     ISBN: "ISBN 6",
//     Price: 20,
//     DiscountPercentage: 15,
//     PublishedDate: new Date("2022-06-01"),
//     PageCount: 150,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 20,
//     AuthorId: 6,
//     AuthorName: "Author Six",
//     PublisherId: 6,
//     PublisherName: "Publisher Six",
//     CategoryIds: [2],
//     CategoryNames: ["Science"],
//     IsActive: true,
//     Rating: 4.0,
//   },
//   {
//     Id: 7,
//     Title: "Book 7",
//     Description: "Description 7",
//     ISBN: "ISBN 7",
//     Price: 20,
//     DiscountPercentage: 15,
//     PublishedDate: new Date("2022-06-01"),
//     PageCount: 150,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 20,
//     AuthorId: 7,
//     AuthorName: "Author Seven",
//     PublisherId: 7,
//     PublisherName: "Publisher Seven",
//     CategoryIds: [2],
//     CategoryNames: ["Science"],
//     IsActive: true,
//     Rating: 4.0,
//   },
//   {
//     Id: 8,
//     Title: "Book 8",
//     Description: "Description 8",
//     ISBN: "ISBN 8",
//     Price: 20,
//     DiscountPercentage: 15,
//     PublishedDate: new Date("2022-06-01"),
//     PageCount: 150,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 20,
//     AuthorId: 8,
//     AuthorName: "Author Eight",
//     PublisherId: 8,
//     PublisherName: "Publisher Eight",
//     CategoryIds: [2],
//     CategoryNames: ["Science"],
//     IsActive: true,
//     Rating: 4.0,
//   },
//   {
//     Id: 9,
//     Title: "Book 9",
//     Description: "Description 9",
//     ISBN: "ISBN 9",
//     Price: 20,
//     DiscountPercentage: 15,
//     PublishedDate: new Date("2022-06-01"),
//     PageCount: 150,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 20,
//     AuthorId: 9,
//     AuthorName: "Author Nine",
//     PublisherId: 9,
//     PublisherName: "Publisher Nine",
//     CategoryIds: [2],
//     CategoryNames: ["Science"],
//     IsActive: true,
//     Rating: 4.0,
//   },
//   {
//     Id: 10,
//     Title: "Book 10",
//     Description: "Description 10",
//     ISBN: "ISBN 10",
//     Price: 20,
//     DiscountPercentage: 15,
//     PublishedDate: new Date("2022-06-01"),
//     PageCount: 150,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 20,
//     AuthorId: 10,
//     AuthorName: "Author Ten",
//     PublisherId: 10,
//     PublisherName: "Publisher Ten",
//     CategoryIds: [2],
//     CategoryNames: ["Science"],
//     IsActive: true,
//     Rating: 4.0,
//   },
//   {
//     Id: 11,
//     Title: "Book 11",
//     Description: "Description 11",
//     ISBN: "ISBN 11",
//     Price: 20,
//     DiscountPercentage: 15,
//     PublishedDate: new Date("2022-06-01"),
//     PageCount: 150,
//     Language: bookLang.en,
//     CoverImageUrl: "/images/bookImage.png",
//     Format: "Paperback",
//     StockQuantity: 20,
//     AuthorId: 11,
//     AuthorName: "Author Eleven",
//     PublisherId: 11,
//     PublisherName: "Publisher Eleven",
//     CategoryIds: [2],
//     CategoryNames: ["Science"],
//     IsActive: true,
//     Rating: 4.0,
//   },
// ];
