import { bookType } from "../book-model/booktType";
import { Ibook } from "../book-model/Ibook";

export const Books : Ibook[] = [
  {
   Id : 1,
   Title : "Book 1",
   Description : "Description 1",
   ISBN : "ISBN 1",
   Price : 10,
   DiscountPercentage : 10,
   CoverImageUrl : "/images/bookImage.png",
   PageCount : 100,
   PublishDate : "2022-01-01",
   Language : "English",
   Format : "Hardcover",
   StockQuantity : 10,
   IsActive : true,
   ViewCount : 10,
   SalesCount : 10,
   AutherId : 1,
   PublisherId : 1,
   CategoryId : 1,
   bookType : bookType.readable
  },
  {
    Id : 2,
    Title : "Book 2",
    Description : "Description 2",
    ISBN : "ISBN 2",
    Price : 20,
    DiscountPercentage : 20,
    CoverImageUrl : "/images/bookImage.png",
    PageCount : 200,
    PublishDate : "2022-01-01",
    Language : "English",
    Format : "Hardcover",
    StockQuantity : 20,
    IsActive : true,
    ViewCount : 20,
    SalesCount : 20,
    AutherId : 2,
    PublisherId : 2,
    CategoryId : 2,
    bookType : bookType.purchasable
   },
   {
    Id: 3,
    Title: 'Book 3',
    Description: 'Description 3',
    ISBN: 'ISBN 3',
    Price: 30,
    DiscountPercentage: 15,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 150,
    PublishDate: '2022-03-01',
    Language: 'French',
    Format: 'Paperback',
    StockQuantity: 12,
    IsActive: false,
    ViewCount: 20,
    SalesCount: 5,
    AutherId: 3,
    PublisherId: 3,
    CategoryId: 2,
    bookType: bookType.purchasable,
  },
  {
    Id: 4,
    Title: 'Book 4',
    Description: 'Description 4',
    ISBN: 'ISBN 4',
    Price: 40,
    DiscountPercentage: 8,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 120,
    PublishDate: '2022-04-01',
    Language: 'Arabic',
    Format: 'Hardcover',
    StockQuantity: 18,
    IsActive: true,
    ViewCount: 25,
    SalesCount: 12,
    AutherId: 4,
    PublisherId: 2,
    CategoryId: 1,
    bookType: bookType.readable,
  },
  {
    Id: 5,
    Title: 'Book 5',
    Description: 'Description 5',
    ISBN: 'ISBN 5',
    Price: 22,
    DiscountPercentage: 5,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 90,
    PublishDate: '2022-05-01',
    Language: 'English',
    Format: 'eBook',
    StockQuantity: 30,
    IsActive: true,
    ViewCount: 40,
    SalesCount: 18,
    AutherId: 1,
    PublisherId: 4,
    CategoryId: 3,
    bookType: bookType.audio,
  },
  {
    Id: 6,
    Title: 'Book 6',
    Description: 'Description 6',
    ISBN: 'ISBN 6',
    Price: 35,
    DiscountPercentage: 12,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 110,
    PublishDate: '2022-06-01',
    Language: 'German',
    Format: 'Paperback',
    StockQuantity: 14,
    IsActive: false,
    ViewCount: 10,
    SalesCount: 7,
    AutherId: 5,
    PublisherId: 5,
    CategoryId: 2,
    bookType: bookType.purchasable,
  },
  {
    Id: 7,
    Title: 'Book 7',
    Description: 'Description 7',
    ISBN: 'ISBN 7',
    Price: 27,
    DiscountPercentage: 20,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 140,
    PublishDate: '2022-07-01',
    Language: 'Spanish',
    Format: 'eBook',
    StockQuantity: 10,
    IsActive: true,
    ViewCount: 18,
    SalesCount: 9,
    AutherId: 2,
    PublisherId: 3,
    CategoryId: 1,
    bookType: bookType.audio,
  },
  {
    Id: 8,
    Title: 'Book 8',
    Description: 'Description 8',
    ISBN: 'ISBN 8',
    Price: 18,
    DiscountPercentage: 10,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 80,
    PublishDate: '2022-08-01',
    Language: 'Italian',
    Format: 'Hardcover',
    StockQuantity: 25,
    IsActive: true,
    ViewCount: 22,
    SalesCount: 14,
    AutherId: 6,
    PublisherId: 6,
    CategoryId: 2,
    bookType: bookType.readable,
  },
  {
    Id: 9,
    Title: 'Book 9',
    Description: 'Description 9',
    ISBN: 'ISBN 9',
    Price: 45,
    DiscountPercentage: 7,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 160,
    PublishDate: '2022-09-01',
    Language: 'English',
    Format: 'Paperback',
    StockQuantity: 8,
    IsActive: false,
    ViewCount: 30,
    SalesCount: 6,
    AutherId: 7,
    PublisherId: 7,
    CategoryId: 3,
    bookType: bookType.purchasable,
  },
  {
    Id: 10,
    Title: 'Book 10',
    Description: 'Description 10',
    ISBN: 'ISBN 10',
    Price: 50,
    DiscountPercentage: 9,
    CoverImageUrl: '/images/bookImage.png',
    PageCount: 200,
    PublishDate: '2022-10-01',
    Language: 'Arabic',
    Format: 'eBook',
    StockQuantity: 20,
    IsActive: true,
    ViewCount: 35,
    SalesCount: 20,
    AutherId: 8,
    PublisherId: 8,
    CategoryId: 1,
    bookType: bookType.audio,
  },

]
