export enum EgyptGovernorates {
  AD_DAQAHLIYAH = 'AD_DAQAHLIYAH',
  AL_BUHAYRAH = 'AL_BUHAYRAH',
  AL_GHARBIYAH = 'AL_GHARBIYAH',
  AL_ISKANDARIYAH = 'AL_ISKANDARIYAH',
  AL_ISMAILIA = 'AL_ISMAILIA',
  AL_MINUFIYAH = 'AL_MINUFIYAH',
  AL_QALYUBIYAH = 'AL_QALYUBIYAH',
  ASH_SHARQIYAH = 'ASH_SHARQIYAH',
  DUMYAT = 'DUMYAT',
  KAFR_ASH_SHAYKH = 'KAFR_ASH_SHAYKH',
  AL_FAYYUM = 'AL_FAYYUM',
  AL_MINYA = 'AL_MINYA',
  ASYUT = 'ASYUT',
  SUHAJ = 'SUHAJ',
  QINA = 'QINA',
  AL_UQSUR = 'AL_UQSUR',
  ASWAN = 'ASWAN',
  BANI_SUWAYF = 'BANI_SUWAYF',
  AL_QAHIRAH = 'AL_QAHIRAH',
  AL_JIZAH = 'AL_JIZAH',
  BUR_SAID = 'BUR_SAID',
  AS_SUWAYS = 'AS_SUWAYS',
  AL_BAHR_AL_AHMAR = 'AL_BAHR_AL_AHMAR',
  AL_WADI_AL_JADID = 'AL_WADI_AL_JADID',
  MATRUH = 'MATRUH',
  SHAMAL_SINA = 'SHAMAL_SINA',
  JANUB_SINA = 'JANUB_SINA'
}

export const GovernorateDisplayNames: Record<EgyptGovernorates, string> = {
  [EgyptGovernorates.AD_DAQAHLIYAH]: 'الدقهلية',
  [EgyptGovernorates.AL_BUHAYRAH]: 'البحيرة',
  [EgyptGovernorates.AL_GHARBIYAH]: 'الغربية',
  [EgyptGovernorates.AL_ISKANDARIYAH]: 'الإسكندرية',
  [EgyptGovernorates.AL_ISMAILIA]: 'الإسماعيلية',
  [EgyptGovernorates.AL_MINUFIYAH]: 'المنوفية',
  [EgyptGovernorates.AL_QALYUBIYAH]: 'القليوبية',
  [EgyptGovernorates.ASH_SHARQIYAH]: 'الشرقية',
  [EgyptGovernorates.DUMYAT]: 'دمياط',
  [EgyptGovernorates.KAFR_ASH_SHAYKH]: 'كفر الشيخ',
  [EgyptGovernorates.AL_FAYYUM]: 'الفيوم',
  [EgyptGovernorates.AL_MINYA]: 'المنيا',
  [EgyptGovernorates.ASYUT]: 'أسيوط',
  [EgyptGovernorates.SUHAJ]: 'سوهاج',
  [EgyptGovernorates.QINA]: 'قنا',
  [EgyptGovernorates.AL_UQSUR]: 'الأقصر',
  [EgyptGovernorates.ASWAN]: 'أسوان',
  [EgyptGovernorates.BANI_SUWAYF]: 'بني سويف',
  [EgyptGovernorates.AL_QAHIRAH]: 'القاهرة',
  [EgyptGovernorates.AL_JIZAH]: 'الجيزة',
  [EgyptGovernorates.BUR_SAID]: 'بورسعيد',
  [EgyptGovernorates.AS_SUWAYS]: 'السويس',
  [EgyptGovernorates.AL_BAHR_AL_AHMAR]: 'البحر الأحمر',
  [EgyptGovernorates.AL_WADI_AL_JADID]: 'الوادي الجديد',
  [EgyptGovernorates.MATRUH]: 'مطروح',
  [EgyptGovernorates.SHAMAL_SINA]: 'شمال سيناء',
  [EgyptGovernorates.JANUB_SINA]: 'جنوب سيناء'
};